name: Publish

on:
  release:
    types: [published]

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7
      with:
        ref: build

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
        registry-url: "https://registry.npmjs.org/"
    
    - name: Install Dependencies
      run: |
        corepack enable
        pnpm install
      env:
        CI: true

    - name: Publish Package
      run: pnpm publish --access public --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: build

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
        registry-url: "https://npm.pkg.github.com"

    - name: Install Dependencies
      run: |
        corepack enable
        pnpm install
      env:
        CI: true

    - name: Publish Package
      run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
